#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/ssh

- name: Add SSH public key
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', 'id_ed25519.pub') }}"